import type {
  LearnConcept,
  DsmCategory,
  DisorderProfile,
  GlossaryEntry,
  PsychoticDomain,
  NeurotransmitterProfile,
  GeneProfile,
  WorldviewTaxonomyEntry,
  BrainAtlasComparison,
  MechanismPanel,
} from "@/lib/types";
import { glossaryEntries as richGlossaryEntries } from "@/lib/glossaryData";

export const LEARN_CONCEPTS: LearnConcept[] = [
  {
    emoji: "⚡",
    title: "Kindling Model",
    summary: "Why episodes beget episodes",
    detail:
      "In 1973, Robert Post proposed that mood episodes in bipolar disorder can be modelled like seizure kindling in animals. Each episode lowers the neurobiological threshold for the next. In LimbicLab, every episode increments the kindling index, lowering the threshold parameter in the ODE system.",
  },
  {
    emoji: "🧬",
    title: "Polygenic Risk",
    summary: "Many small genetic variants combine to create vulnerability",
    detail:
      "Bipolar disorder is highly heritable, but no single gene determines risk. Hundreds of common variants combine into a polygenic risk score (PRS). Variants near genes like CACNA1C, ANK3, and NRXN1 are among the best replicated.",
  },
  {
    emoji: "🌿",
    title: "Cannabis & the Endocannabinoid System",
    summary: "CB1 receptors, dopamine, and mood destabilisation",
    detail:
      "THC is a partial agonist at CB1 receptors and can disinhibit dopaminergic signaling in vulnerable circuits. High-CBD strains may partly attenuate this signal. In at-risk populations, heavy use is associated with greater mood-instability and psychosis-spectrum risk.",
  },
  {
    emoji: "🔬",
    title: "Neurotransmitter ODE Model",
    summary: "Dopamine, serotonin, and GABA as coupled differential equations",
    detail:
      "LimbicLab uses a three-variable Euler-integrated ODE. Dopamine (D), serotonin (S), and GABA (G) each evolve over time with cross-coupling terms and Gaussian noise to represent stochastic biology.",
  },
  {
    emoji: "📊",
    title: "Risk Score Composition",
    summary: "How the 0-100 composite score is calculated",
    detail:
      "The educational risk score combines polygenic loading, kindling index, episode burden, and cannabis exposure. It is designed for learning and not for diagnosis or clinical decision making.",
  },
  {
    emoji: "🧠",
    title: "Mood Valence & Arousal",
    summary: "The two-dimensional mood model",
    detail:
      "Mood is represented using valence and arousal axes. Discrete labels (euthymic, hypomanic, manic, depressed, mixed) are generated by threshold rules from continuous trajectories.",
  },
];

export const DSM5_CATEGORIES: DsmCategory[] = [
  {
    emoji: "🧭",
    family: "Bipolar and Related Disorders",
    focus:
      "Episodes of elevated mood and energy with shifts in depressive severity over time.",
    examples: ["Bipolar I disorder", "Bipolar II disorder", "Cyclothymic disorder"],
  },
  {
    emoji: "🌧️",
    family: "Depressive Disorders",
    focus:
      "Low mood, anhedonia, and neurovegetative/cognitive changes that impair daily functioning.",
    examples: ["Major depressive disorder", "Persistent depressive disorder"],
  },
  {
    emoji: "⚠️",
    family: "Anxiety Disorders",
    focus:
      "Excessive fear and worry with physiological arousal and behavioral avoidance.",
    examples: ["Generalized anxiety disorder", "Panic disorder", "Social anxiety disorder"],
  },
  {
    emoji: "🛡️",
    family: "Trauma- and Stressor-Related Disorders",
    focus:
      "Symptoms after severe stress exposure, including intrusion, avoidance, and hyperarousal.",
    examples: ["Post-traumatic stress disorder", "Adjustment disorder"],
  },
  {
    emoji: "🔁",
    family: "Obsessive-Compulsive and Related Disorders",
    focus:
      "Intrusions and repetitive rituals aimed at reducing distress or preventing feared outcomes.",
    examples: ["Obsessive-compulsive disorder", "Body dysmorphic disorder"],
  },
  {
    emoji: "🧩",
    family: "Schizophrenia Spectrum and Other Psychotic Disorders",
    focus:
      "Disturbances in thought, perception, reality testing, and goal-directed behavior.",
    examples: [
      "Schizophrenia",
      "Schizoaffective disorder",
      "Schizophreniform disorder",
      "Brief psychotic disorder",
    ],
  },
  {
    emoji: "🍃",
    family: "Substance-Related and Addictive Disorders",
    focus:
      "Compulsive use despite harm with tolerance, withdrawal, and loss of control.",
    examples: ["Cannabis use disorder", "Alcohol use disorder", "Stimulant use disorder"],
  },
  {
    emoji: "🧠",
    family: "Neurodevelopmental Disorders",
    focus:
      "Early-onset conditions affecting cognition, communication, attention, and behavior.",
    examples: ["ADHD", "Autism spectrum disorder", "Intellectual disability"],
  },
  {
    emoji: "👤",
    family: "Personality Disorders",
    focus:
      "Enduring, inflexible personality patterns causing chronic distress and impairment.",
    examples: ["Borderline personality disorder", "Obsessive-compulsive personality disorder"],
  },
];

export const DISORDER_SPOTLIGHTS: DisorderProfile[] = [
  {
    name: "Schizophrenia",
    family: "Schizophrenia spectrum",
    keyFeatures:
      "Persistent psychotic symptoms may include delusions, hallucinations, disorganized speech/behavior, and negative symptoms such as avolition.",
    typicalOnset: "Late adolescence to early adulthood",
    contextNote:
      "Course and severity are influenced by social support, trauma exposure, substance use, and treatment access.",
    citations: ["DSM-5-TR (APA, 2022)", "NIMH Overview"],
  },
  {
    name: "Schizoaffective Disorder",
    family: "Schizophrenia spectrum",
    keyFeatures:
      "Psychotic symptoms occur with major mood episodes, with at least one period of psychosis that is not exclusively mood-driven.",
    typicalOnset: "Early adulthood",
    contextNote:
      "Mood symptoms and psychosis can fluctuate in prominence across time.",
    citations: ["DSM-5-TR (APA, 2022)", "Malaspina et al., 2013"],
  },
  {
    name: "Schizophreniform Disorder",
    family: "Schizophrenia spectrum",
    keyFeatures:
      "Schizophrenia-like symptom profile with shorter duration than chronic schizophrenia.",
    typicalOnset: "Late adolescence to early adulthood",
    contextNote:
      "Early intervention may improve longer-term functioning and recovery trajectory.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Brief Psychotic Disorder",
    family: "Schizophrenia spectrum",
    keyFeatures:
      "Abrupt psychotic episode lasting more than one day but less than one month, with eventual return to baseline.",
    typicalOnset: "Can occur across adulthood",
    contextNote:
      "Can be associated with acute stressors or postpartum states in some cases.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Bipolar I Disorder",
    family: "Bipolar and related",
    keyFeatures:
      "At least one manic episode, often with depressive episodes across the lifespan.",
    typicalOnset: "Late adolescence to early adulthood",
    contextNote:
      "Stress load, sleep disruption, and substance exposure can amplify episode recurrence risk.",
    citations: ["DSM-5-TR (APA, 2022)", "Post, 1992"],
  },
  {
    name: "Bipolar II Disorder",
    family: "Bipolar and related",
    keyFeatures:
      "Pattern of hypomanic and major depressive episodes without full mania.",
    typicalOnset: "Late adolescence to early adulthood",
    contextNote:
      "Depressive burden is often substantial and may be under-recognized.",
    citations: ["DSM-5-TR (APA, 2022)", "PGC Bipolar GWAS, 2021"],
  },
  {
    name: "Major Depressive Disorder",
    family: "Depressive disorders",
    keyFeatures:
      "Sustained depressed mood and/or anhedonia with cognitive and somatic symptoms causing impairment.",
    typicalOnset: "Any age; common in adolescence and adulthood",
    contextNote:
      "Risk and recovery are shaped by biology, life events, social determinants, and care access.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Post-Traumatic Stress Disorder",
    family: "Trauma- and stressor-related",
    keyFeatures:
      "Re-experiencing, avoidance, negative mood/cognition changes, and hyperarousal after trauma.",
    typicalOnset: "After exposure to a qualifying traumatic event",
    contextNote:
      "Not all trauma-exposed individuals develop PTSD; resilience and support factors matter.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Obsessive-Compulsive Disorder",
    family: "Obsessive-compulsive and related",
    keyFeatures:
      "Intrusive obsessions and repetitive compulsions that are time-consuming and distressing.",
    typicalOnset: "Often adolescence to early adulthood",
    contextNote:
      "Symptoms are ego-dystonic for many individuals and can respond to evidence-based treatment.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Cannabis Use Disorder",
    family: "Substance-related and addictive",
    keyFeatures:
      "Persistent cannabis use despite harm, with impaired control and role disruption.",
    typicalOnset: "Often adolescence or young adulthood",
    contextNote:
      "Severity and risk are affected by potency, frequency, age of onset, and psychiatric vulnerability.",
    citations: ["DSM-5-TR (APA, 2022)", "Murray et al., 2017"],
  },
];

export const STRESS_DIATHESIS_PARAGRAPHS: string[] = [
  "Bipolar disorder reflects a widely distributed human vulnerability rather than a categorical difference between people. In a stress-diathesis model, sustained stressors, including institutional stress such as incarceration, criminal charges, or repeated law-enforcement contact, can increase the probability of illness expression in vulnerable individuals.",
  "A diagnosis is not a marker of lesser humanity. It describes how biology, environment, and lived experience interact over time.",
];

export const NEUROTRANSMITTER_PROFILES: NeurotransmitterProfile[] = [
  {
    name: "Dopamine",
    primaryRole:
      "Helps the brain assign salience (what matters), learn from reward prediction error, and regulate motivation, movement, and goal-directed behavior.",
    whenLow:
      "Can be associated with reduced drive, less pleasure from normally rewarding activities, cognitive slowing, and in some circuits motor slowing.",
    whenHighOrDysregulated:
      "Excessive or poorly timed dopamine signaling can amplify threat/reward salience and has been linked to manic activation and psychosis-spectrum symptoms in vulnerable people.",
    learningNote:
      "Dopamine is not a simple 'pleasure chemical.' It is a precision-learning and salience signal distributed across multiple pathways.",
  },
  {
    name: "GABA",
    primaryRole:
      "The major inhibitory neurotransmitter in the CNS. It dampens over-excitation and helps stabilize network rhythms needed for attention, emotion regulation, and sleep.",
    whenLow:
      "Reduced inhibitory tone can contribute to hyperarousal, anxiety, poor sleep, sensory overload, and increased vulnerability to excitatory runaway states.",
    whenHighOrDysregulated:
      "Excessive inhibition may present as sedation, slowed cognition, or emotional blunting, depending on which circuits are affected.",
    learningNote:
      "Think of GABA as a braking system: healthy function requires balance with excitatory signaling rather than maximal inhibition.",
  },
  {
    name: "Serotonin",
    primaryRole:
      "Modulates mood, anxiety, impulse control, appetite, pain processing, and sleep-wake timing across widespread brain networks.",
    whenLow:
      "Lower serotonergic tone is associated in some individuals with depressed mood, anxiety, irritability, and reduced stress resilience.",
    whenHighOrDysregulated:
      "Overactivation of serotonergic pathways can cause agitation, GI symptoms, tremor, and in severe medication interactions, serotonin toxicity.",
    learningNote:
      "Serotonin is a broad modulatory system, not a single mood dial; effects depend on receptor subtype, brain region, and timescale.",
  },
];

export const GENE_PRIMER_PARAGRAPHS: string[] = [
  "Genes are segments of DNA that provide instructions for building proteins. Proteins help neurons grow, communicate, and adapt, so genetic variation can influence how brain circuits develop and respond to stress.",
  "In psychiatry, risk is usually polygenic: many common variants each contribute a very small effect. Genes are not destiny; they shift probability in combination with environment, development, sleep, trauma load, substance exposure, and social context.",
];

export const PRIORITY_GENE_PROFILES: GeneProfile[] = [
  {
    symbol: "CACNA1C",
    fullName: "Calcium Voltage-Gated Channel Subunit Alpha1 C",
    whatItDoes:
      "Encodes a major subunit of L-type voltage-gated calcium channels, which regulate calcium entry during neuronal firing and influence excitability, synaptic plasticity, and gene transcription.",
    whyStudiedInPsychiatry:
      "Common variants near CACNA1C repeatedly appear in large GWAS of bipolar disorder and other mood/psychosis-related phenotypes.",
    plainLanguageTakeaway:
      "CACNA1C affects how strongly neurons respond and adapt, making it a biologically plausible contributor to mood-circuit sensitivity.",
  },
  {
    symbol: "ANK3",
    fullName: "Ankyrin 3",
    whatItDoes:
      "Helps organize ion channels, especially at the axon initial segment and nodes of Ranvier, which are key for action-potential initiation and stable signal conduction.",
    whyStudiedInPsychiatry:
      "ANK3 is one of the most consistently replicated bipolar-associated loci across multiple genetic studies.",
    plainLanguageTakeaway:
      "ANK3 supports the electrical architecture neurons use to fire reliably, so variation may alter network stability in vulnerable circuits.",
  },
  {
    symbol: "NRXN1",
    fullName: "Neurexin 1",
    whatItDoes:
      "Encodes a synaptic adhesion molecule involved in how neurons form and maintain synaptic connections and coordinate neurotransmitter release.",
    whyStudiedInPsychiatry:
      "NRXN1 variation, including some rare structural variants, has been linked to neurodevelopmental and psychosis-spectrum risk in subsets of individuals.",
    plainLanguageTakeaway:
      "NRXN1 relates to synapse wiring quality, making it relevant when studying how communication across brain networks can become less robust.",
  },
];

export const GLOSSARY_TERMS: GlossaryEntry[] = [
  {
    term: "Bipolar Disorder",
    definition:
      "A mood disorder characterized by episodes of mania or hypomania and episodes of depression.",
  },
  {
    term: "Schizophrenia",
    definition:
      "A psychotic disorder involving disruptions in perception, thought, and behavior, often with social or occupational decline.",
  },
  {
    term: "Schizoaffective Disorder",
    definition:
      "A condition with both psychotic symptoms and major mood episodes, with some psychosis occurring outside mood episodes.",
  },
  {
    term: "Stress-Diathesis Model",
    definition:
      "A framework in which underlying vulnerability interacts with environmental stress to produce symptom expression.",
  },
  {
    term: "Psychosis",
    definition:
      "A clinical state involving impaired reality testing, such as delusions or hallucinations.",
  },
  {
    term: "Polygenic Risk Score (PRS)",
    definition:
      "A summary score of genetic liability computed from many common variants with small individual effects.",
  },
  {
    term: "Kindling",
    definition:
      "A process in which repeated episodes can lower the threshold for future episodes over time.",
  },
  {
    term: "CB1 Receptor",
    definition:
      "The primary cannabinoid receptor in the brain, strongly involved in THC effects.",
  },
  {
    term: "Dopamine",
    definition:
      "A neurotransmitter involved in salience, motivation, reward-based learning, movement, and goal-directed behavior.",
  },
  {
    term: "GABA",
    definition:
      "The brain's main inhibitory neurotransmitter, helping regulate excitability and stabilize neural signaling.",
  },
  {
    term: "Serotonin",
    definition:
      "A broadly modulatory neurotransmitter involved in mood, anxiety regulation, impulse control, sleep, appetite, and stress responsiveness.",
  },
  {
    term: "CACNA1C",
    definition:
      "A gene encoding a key subunit of an L-type calcium channel; variants near this gene are repeatedly associated with bipolar risk in large studies.",
  },
  {
    term: "ANK3",
    definition:
      "A gene involved in organizing ion-channel architecture in neurons, important for reliable action-potential firing.",
  },
  {
    term: "NRXN1",
    definition:
      "A synaptic adhesion gene involved in neuron-to-neuron connectivity and neurotransmitter signaling at synapses.",
  },
  {
    term: "ODE (Ordinary Differential Equation)",
    definition:
      "A mathematical equation used to model how variables change continuously over time.",
  },
  {
    term: "Stochastic",
    definition:
      "Containing random variation; stochastic simulations can produce slightly different outputs each run.",
  },
  ...richGlossaryEntries
    .filter(
      (entry) =>
        entry.term === "Cognitive Dissonance" || entry.term === "Ideological Friction"
    )
    .map((entry) => ({
      term: entry.term,
      definition: entry.plainDefinition,
    }))
    .filter(
      (entry, index, list) => list.findIndex((item) => item.term === entry.term) === index
    ),
];

export const LEARN_REFERENCES: string[] = [
  "American Psychiatric Association. (2022). Diagnostic and Statistical Manual of Mental Disorders (5th ed., text rev.; DSM-5-TR).",
  "Post, R.M. (1992). Transduction of psychosocial stress into the neurobiology of recurrent affective disorder. American Journal of Psychiatry, 149(8), 999-1010.",
  "Bipolar Disorder Working Group of the Psychiatric Genomics Consortium (2021). Large-scale GWAS meta-analysis of bipolar disorder identifies 64 loci and clarifies the genetic basis of bipolar subtypes. Nature Genetics.",
  "Murray, R.M. et al. (2017). Traditional marijuana, high-potency cannabis and synthetic cannabinoids: increasing risk for psychosis. World Psychiatry, 16(2), 146-149.",
  "Goldbeter, A. (1996). Biochemical Oscillations and Cellular Rhythms. Cambridge University Press.",
  "Russell, J.A. (1980). A circumplex model of affect. Journal of Personality and Social Psychology, 39(6), 1161-1178.",
];

export const WORLDVIEW_CASE_STUDY_INTRO: string[] = [
  "This case-study section uses Satanism as an example of how a worldview can be analyzed at three levels at once: symbolic meaning, ritual form, and measurable brain-body mechanisms. The key scientific point is that no study has identified a unique Satanism biomarker. What can be studied are threat processing, reward learning, social bonding, dissociation, trauma load, and moral cognition.",
  "That distinction matters because non-theistic Satanic movements vary widely. Some are primarily political or philosophical identities, while other settings can involve fear-heavy ritual, coercion, pain, humiliation, or trauma. The neurobiology tracks the experience and conditioning environment more than the label itself.",
];

export const WORLDVIEW_TAXONOMY: WorldviewTaxonomyEntry[] = [
  {
    name: "Theistic / Ritual Satanism",
    summary: "Literal devotion to Satanic or demonic beings, often through occult ceremonial practice.",
    worldview:
      "Usually organized around adversarial spirituality, taboo, hidden power, transgression, and in some cases death-centered symbolism.",
    psychologicalProfile:
      "Often overlaps with high openness to unusual experience, attraction to liminal identity, and strong symbolic thinking. Clinical risk rises when the environment becomes coercive, humiliating, or trauma-saturated.",
    evidenceNote:
      "Evidence is strongest for general trauma and fear-conditioning mechanisms, not for the label itself as a psychiatric predictor.",
  },
  {
    name: "LaVeyan / Atheistic Satanism",
    summary: "A non-theistic philosophy centered on self-deification, pride, and radical individualism.",
    worldview:
      "Treats Satan as a symbol of rebellion, carnality, self-authorship, and strategic egoism rather than a literal deity.",
    psychologicalProfile:
      "More closely tied to anti-authoritarian identity, reactance, and self-enhancement motives than to occult belief. The main psychological question is whether self-assertion remains adaptive or hardens into entitlement and chronic antagonism.",
    evidenceNote:
      "There is little evidence for disorder-specific outcomes from non-theistic identification alone.",
  },
  {
    name: "The Satanic Temple",
    summary: "A non-theistic movement using Satanic imagery for legal activism, satire, and minority-rights politics.",
    worldview:
      "Frames Satan as a literary-political emblem of resistance to arbitrary authority and defense of pluralism, autonomy, and church-state separation.",
    psychologicalProfile:
      "Typically better explained through civic activism, identity-based solidarity, and oppositional politics than through dark ritual psychology.",
    evidenceNote:
      "Any attempt to pathologize this group from symbolism alone would overreach the evidence.",
  },
  {
    name: "Luciferianism",
    summary: "A related but distinct tradition focused on illumination, individuation, and esoteric self-cultivation.",
    worldview:
      "Often emphasizes knowledge, autonomy, adversarial inquiry, and elite self-development rather than the raw inversionism of some Satanic currents.",
    psychologicalProfile:
      "Common themes include high openness, intellectualization, and identity built around symbolic depth. Risks depend on whether the system promotes integration or glorified domination.",
    evidenceNote:
      "The main psychological distinction is not Satan vs. Lucifer language, but whether practice is integrating, grandiose, coercive, or traumatic.",
  },
];

export const WORLDVIEW_BRAIN_MAP: BrainAtlasComparison[] = [
  {
    region: "Amygdala",
    atlasHash: "region-amygdala",
    role: "Rapid threat detection, emotional salience, and fear learning.",
    positiveRitualPattern:
      "In supportive ritual, amygdala activation is buffered by predictability, social safety, and top-down meaning, so arousal stays bounded.",
    threatRitualPattern:
      "In fear-heavy ritual, dark imagery, ambiguity, and menace can strengthen threat tagging and cue-dependent vigilance over time.",
  },
  {
    region: "Prefrontal Cortex",
    atlasHash: "region-prefrontal-cortex",
    role: "Top-down appraisal, impulse control, and reinterpretation of arousal.",
    positiveRitualPattern:
      "Healing ritual can support prefrontal regulation by making sensations legible and manageable within a coherent framework.",
    threatRitualPattern:
      "Under chronic threat, prefrontal regulation weakens, making reactions more stimulus-bound and less reflective.",
  },
  {
    region: "Hippocampus",
    atlasHash: "region-hippocampus",
    role: "Contextual memory, autobiographical encoding, and linking cues to time and place.",
    positiveRitualPattern:
      "Safe ritual can stabilize memory through structured narrative and contextual coherence.",
    threatRitualPattern:
      "Traumatic ritual can fragment contextual encoding, especially when fear, dissociation, or sleep disruption are present.",
  },
  {
    region: "Hypothalamus",
    atlasHash: "region-hypothalamus",
    role: "Links brain state to hormones, autonomic output, and the HPA stress axis.",
    positiveRitualPattern:
      "Breath pacing, social buffering, and predictable sequence can reduce endocrine alarm signals over time.",
    threatRitualPattern:
      "Coercive or dread-based settings may keep cortisol signaling elevated and disrupt recovery rhythms.",
  },
  {
    region: "Nucleus Accumbens",
    atlasHash: "region-nucleus-accumbens",
    role: "Reward anticipation, reinforcement learning, and motivation.",
    positiveRitualPattern:
      "Belonging, music, synchrony, and meaning can reinforce prosocial ritual participation.",
    threatRitualPattern:
      "Power fantasy, taboo transgression, and intermittent intensity can also become reinforcing, even when the ritual is aversive overall.",
  },
  {
    region: "Insula",
    atlasHash: "region-insula",
    role: "Interoception, body-state awareness, and felt meaning.",
    positiveRitualPattern:
      "The insula can help translate breath, posture, and rhythm into grounded self-awareness.",
    threatRitualPattern:
      "When ritual amplifies dread, pain, or contamination themes, body sensations can be interpreted as proof of danger or possession.",
  },
];

export const WORLDVIEW_MECHANISM_PANELS: MechanismPanel[] = [
  {
    title: "Dopamine: D1 / D2 salience and reinforcement",
    detail:
      "Intense ritual can recruit mesocorticolimbic dopamine systems through novelty, status, taboo, group intensity, and emotionally charged expectancy. In darker settings, power and transgression may become strongly tagged as salient.",
    clinicalMeaning:
      "The relevant risk is not a 'Satanic dopamine receptor' but a habit loop in which reward, identity, and arousal become tightly coupled.",
  },
  {
    title: "Norepinephrine: noradrenergic threat arousal",
    detail:
      "The locus coeruleus-norepinephrine system sharpens vigilance, sensory gain, and memory for threat. Dark symbolism, menace, uncertainty, and death imagery can all intensify this response when believed or emotionally primed.",
    clinicalMeaning:
      "Repeated activation can bias a person toward hypervigilance, exaggerated significance attribution, and difficulty returning to baseline.",
  },
  {
    title: "Serotonin, GABA, glutamate, and altered state intensity",
    detail:
      "Altered states during ritual are more likely when sleep is disrupted, breathing shifts, arousal escalates, or psychoactive substances are involved. Serotonergic tone, inhibitory GABA signaling, and glutamatergic excitation help shape how controllable those states feel.",
    clinicalMeaning:
      "The strongest practical distinction is grounded regulation versus dysregulated arousal with derealization, panic, or dissociation.",
  },
  {
    title: "Cortisol, oxytocin, and endogenous opioids",
    detail:
      "Threat-heavy settings can increase cortisol and allostatic load, while synchronized group ritual can elevate bonding signals and, in painful ordeals, endogenous opioid release. This mix helps explain why frightening practices can still feel compelling or meaningful to participants.",
    clinicalMeaning:
      "Clinically, bonding does not prove safety. High-control groups can combine in-group warmth with fear, shame, and coercion.",
  },
  {
    title: "Genes and epigenetics under chronic stress",
    detail:
      "If practice involves chronic fear or trauma, literature on FKBP5, NR3C1 methylation, BDNF suppression, and inflammatory markers such as IL-6 and TNF-alpha becomes relevant. These are stress-trauma pathways, not belief-specific signatures.",
    clinicalMeaning:
      "Any gene-expression discussion should be framed as mechanistic plausibility based on adversity exposure, not as evidence that a worldview directly rewires DNA in a unique way.",
  },
  {
    title: "Recovery and plasticity",
    detail:
      "After prolonged threat conditioning, recovery depends on safe exposure, coherent meaning-making, trauma treatment, sleep restoration, and rebuilding agency without grandiose or contamination narratives.",
    clinicalMeaning:
      "Trauma-focused CBT, EMDR, sleep stabilization, and dependable social support are more evidence-based than ideology-specific healing claims.",
  },
];

export const WORLDVIEW_EVIDENCE_BOUNDARIES: string[] = [
  "No peer-reviewed literature supports a unique molecular or receptor-level profile for Satanism as a category.",
  "Claims about psychopathy, borderline traits, depression, or suicidal ideation need to be tied to trauma exposure, coercion, isolation, or pre-existing vulnerability rather than assumed from membership alone.",
  "Reports of ritual abuse should be approached with trauma-informed clinical care and careful evidentiary standards. Trauma symptoms can be real even when surrounding narratives are disputed or contaminated by suggestion.",
  "The best-supported moral-psychology finding in this area concerns demonization and 'pure evil' framing, which can reduce empathy and increase punitive cognition on all sides of a conflict.",
];

export const WORLDVIEW_CASE_STUDY_REFERENCES: string[] = [
  "Hobson, N.M., Schroeder, J., Risen, J.L., Xygalatas, D., & Inzlicht, M. (2018). The psychology of rituals: An integrative review and process-based framework. Personality and Social Psychology Review, 22(3), 260-284.",
  "Sara, S.J. (2009). The locus coeruleus and noradrenergic modulation of cognition. Nature Reviews Neuroscience, 10(3), 211-223.",
  "Lupien, S.J., McEwen, B.S., Gunnar, M.R., & Heim, C. (2009). Effects of stress throughout the lifespan on the brain, behaviour and cognition. Nature Reviews Neuroscience, 10(6), 434-445.",
  "Klengel, T., Mehta, D., Anacker, C., et al. (2013). Allele-specific FKBP5 DNA demethylation mediates gene-childhood trauma interactions. Nature Neuroscience, 16(1), 33-41.",
  "McGowan, P.O., Sasaki, A., D'Alessio, A.C., et al. (2009). Epigenetic regulation of the glucocorticoid receptor in human brain associates with childhood abuse. Nature Neuroscience, 12(3), 342-348.",
  "Slavich, G.M., & Irwin, M.R. (2014). From stress to inflammation and major depressive disorder: A social signal transduction theory of depression. Psychological Bulletin, 140(3), 774-815.",
  "van Elk, M., & Aleman, A. (2017). Brain mechanisms in religion and spirituality: An integrative predictive processing framework. Neuroscience & Biobehavioral Reviews, 73, 359-378.",
  "Cusack, K., Jonas, D.E., Forneris, C.A., et al. (2016). Psychological treatments for adults with posttraumatic stress disorder: A systematic review and meta-analysis. Clinical Psychology Review, 43, 128-141.",
  "Brewer, J.A., Worhunsky, P.D., Gray, J.R., Tang, Y.Y., Weber, J., & Kober, H. (2011). Meditation experience is associated with differences in default mode network activity and connectivity. PNAS, 108(50), 20254-20259.",
];

export const SOCIAL_PERCEPTION_INTRO: string[] = [
  "Ambiguous social scenes can contain overlapping cues: attraction, rejection, rivalry, exclusion, teasing, dominance display, or uncertainty about intent. In lab settings, researchers often use short video clips or staged interactions to test how viewers interpret those signals in real time.",
  "A standard approach combines physiology with self-report. Heart rate and skin conductance are recorded while participants watch the clip, then viewers rate perceived intent and emotional response. Those ratings can include threat, attraction, discomfort, jealousy, anger, embarrassment, confusion, or felt rejection. The point is to study arousal together with appraisal, not to assume that one visible behavior reveals a single motive or stable moral character.",
];

export const SOCIAL_PERCEPTION_PROTOCOL = [
  {
    title: "Stimulus design",
    detail:
      "Use short video clips showing ambiguous interpersonal dynamics: teasing vs. humiliation, flirtation vs. manipulation, status display vs. self-presentation, or inclusion vs. exclusion.",
  },
  {
    title: "Biophysical recording",
    detail:
      "Measure heart rate and skin conductance continuously during clip viewing. If available, add eye tracking or facial EMG to estimate attentional capture and positive-vs-negative facial response.",
  },
  {
    title: "Self-report after each clip",
    detail:
      "Ask viewers to rate perceived intent, emotional arousal, threat, attraction, disgust, confusion, and whether the scene felt rejecting, mocking, coercive, sexually charged, or socially competitive.",
  },
  {
    title: "Pattern analysis",
    detail:
      "Correlate physiological changes with subjective ratings to distinguish high arousal linked to threat appraisal from high arousal linked to attraction, curiosity, jealousy, or unresolved uncertainty.",
  },
];

export const SOCIAL_PERCEPTION_SIGNAL_GUIDE = [
  {
    label: "Heart rate",
    summary:
      "Tracks overall autonomic engagement, orienting, and stress-related activation during a social scene.",
    caution:
      "Heart rate alone cannot determine whether the viewer is feeling fear, anger, attraction, embarrassment, jealousy, or surprise.",
  },
  {
    label: "Skin conductance",
    summary:
      "Captures sympathetic arousal and is sensitive to emotionally significant or attention-grabbing moments.",
    caution:
      "Higher conductance indicates intensity, not moral truth and not a specific emotion by itself.",
  },
  {
    label: "Self-report",
    summary:
      "Adds the viewer's conscious interpretation: rejection, attraction, confusion, admiration, intimidation, or disgust.",
    caution:
      "People can underreport shame, jealousy, sexual interest, or hostility, so self-report is useful but incomplete.",
  },
];

export const SOCIAL_PERCEPTION_EVIDENCE_BOUNDARIES: string[] = [
  "Relational aggression, mockery, exclusion, and ambiguous courtship behavior are not exclusive to one gender. They should be studied as social strategies that can appear across people and contexts.",
  "Physiological arousal is not the same thing as sexual arousal. A strong biometric response may reflect threat, uncertainty, anger, attention capture, embarrassment, or attraction.",
  "Bragging about multiple partners or options can function as status signaling, insecurity management, impression management, or competitive display. It should not be treated as direct proof of inner character from a single observation.",
  "When researchers study dating, rejection, jealousy, or attraction, the strongest designs pair physiology with carefully worded self-report and avoid assuming motive from appearance, gender, or one-sided narrative alone.",
];

export const SOCIAL_PERCEPTION_REFERENCES: string[] = [
  "Crick, N.R., & Grotpeter, J.K. (1995). Relational aggression, gender, and social-psychological adjustment. Child Development, 66(3), 710-722.",
  "Downey, G., & Feldman, S.I. (1996). Implications of rejection sensitivity for intimate relationships. Journal of Personality and Social Psychology, 70(6), 1327-1343.",
  "Eisenberger, N.I., Lieberman, M.D., & Williams, K.D. (2003). Does rejection hurt? An fMRI study of social exclusion. Science, 302(5643), 290-292.",
  "Kross, E., Berman, M.G., Mischel, W., Smith, E.E., & Wager, T.D. (2011). Social rejection shares somatosensory representations with physical pain. PNAS, 108(15), 6270-6275.",
  "Bradley, M.M., & Lang, P.J. (2007). Emotion and motivation. In Handbook of Psychophysiology (3rd ed.). Cambridge University Press.",
  "Cacioppo, J.T., Tassinary, L.G., & Berntson, G.G. (Eds.). (2007). Handbook of Psychophysiology (3rd ed.). Cambridge University Press.",
];

export const PSYCHOTIC_SYMPTOM_DOMAINS: PsychoticDomain[] = [
  {
    domain: "Positive symptoms",
    description:
      "Experiences added to baseline cognition/perception such as fixed false beliefs and abnormal sensory experiences.",
    examples: ["Delusions", "Hallucinations", "Disorganized thought content"],
    clinicalImportance:
      "Often drive acute risk, emergency presentation, and need for rapid stabilization.",
  },
  {
    domain: "Negative symptoms",
    description:
      "Reductions in motivated behavior, emotional expression, and social initiative.",
    examples: ["Avolition", "Blunted affect", "Alogia", "Social withdrawal"],
    clinicalImportance:
      "Strongly linked to long-term functional outcomes and quality of life.",
  },
  {
    domain: "Cognitive symptoms",
    description:
      "Difficulties in attention, working memory, processing speed, and executive planning.",
    examples: ["Attention deficits", "Working-memory impairment", "Executive dysfunction"],
    clinicalImportance:
      "Frequently predicts educational, occupational, and daily-living impairment.",
  },
  {
    domain: "Affective symptoms",
    description:
      "Mood symptoms that can overlap with or alternate against psychotic symptoms.",
    examples: ["Depressive episodes", "Manic/hypomanic episodes", "Anxiety symptoms"],
    clinicalImportance:
      "Essential for differential diagnosis, including schizoaffective and mood disorders with psychotic features.",
  },
];
