import type {
  LearnConcept,
  DsmCategory,
  DisorderProfile,
  GlossaryEntry,
  PsychoticDomain,
  NeurotransmitterProfile,
} from "@/lib/types";

export const LEARN_CONCEPTS: LearnConcept[] = [
  {
    emoji: "⚡",
    title: "Kindling Model",
    summary: "Why episodes beget episodes",
    detail:
      "In 1973, Robert Post proposed that mood episodes in bipolar disorder can be modelled like seizure kindling in animals. Each episode lowers the neurobiological threshold for the next. In LimbicLab, every episode increments the kindling index, lowering the threshold parameter in the ODE system.",
  },
  {
    emoji: "🧬",
    title: "Polygenic Risk",
    summary: "Many small genetic variants combine to create vulnerability",
    detail:
      "Bipolar disorder is highly heritable, but no single gene determines risk. Hundreds of common variants combine into a polygenic risk score (PRS). Variants near genes like CACNA1C, ANK3, and NRXN1 are among the best replicated.",
  },
  {
    emoji: "🌿",
    title: "Cannabis & the Endocannabinoid System",
    summary: "CB1 receptors, dopamine, and mood destabilisation",
    detail:
      "THC is a partial agonist at CB1 receptors and can disinhibit dopaminergic signaling in vulnerable circuits. High-CBD strains may partly attenuate this signal. In at-risk populations, heavy use is associated with greater mood-instability and psychosis-spectrum risk.",
  },
  {
    emoji: "🔬",
    title: "Neurotransmitter ODE Model",
    summary: "Dopamine, serotonin, and GABA as coupled differential equations",
    detail:
      "LimbicLab uses a three-variable Euler-integrated ODE. Dopamine (D), serotonin (S), and GABA (G) each evolve over time with cross-coupling terms and Gaussian noise to represent stochastic biology.",
  },
  {
    emoji: "📊",
    title: "Risk Score Composition",
    summary: "How the 0-100 composite score is calculated",
    detail:
      "The educational risk score combines polygenic loading, kindling index, episode burden, and cannabis exposure. It is designed for learning and not for diagnosis or clinical decision making.",
  },
  {
    emoji: "🧠",
    title: "Mood Valence & Arousal",
    summary: "The two-dimensional mood model",
    detail:
      "Mood is represented using valence and arousal axes. Discrete labels (euthymic, hypomanic, manic, depressed, mixed) are generated by threshold rules from continuous trajectories.",
  },
];

export const DSM5_CATEGORIES: DsmCategory[] = [
  {
    emoji: "🧭",
    family: "Bipolar and Related Disorders",
    focus:
      "Episodes of elevated mood and energy with shifts in depressive severity over time.",
    examples: ["Bipolar I disorder", "Bipolar II disorder", "Cyclothymic disorder"],
  },
  {
    emoji: "🌧️",
    family: "Depressive Disorders",
    focus:
      "Low mood, anhedonia, and neurovegetative/cognitive changes that impair daily functioning.",
    examples: ["Major depressive disorder", "Persistent depressive disorder"],
  },
  {
    emoji: "⚠️",
    family: "Anxiety Disorders",
    focus:
      "Excessive fear and worry with physiological arousal and behavioral avoidance.",
    examples: ["Generalized anxiety disorder", "Panic disorder", "Social anxiety disorder"],
  },
  {
    emoji: "🛡️",
    family: "Trauma- and Stressor-Related Disorders",
    focus:
      "Symptoms after severe stress exposure, including intrusion, avoidance, and hyperarousal.",
    examples: ["Post-traumatic stress disorder", "Adjustment disorder"],
  },
  {
    emoji: "🔁",
    family: "Obsessive-Compulsive and Related Disorders",
    focus:
      "Intrusions and repetitive rituals aimed at reducing distress or preventing feared outcomes.",
    examples: ["Obsessive-compulsive disorder", "Body dysmorphic disorder"],
  },
  {
    emoji: "🧩",
    family: "Schizophrenia Spectrum and Other Psychotic Disorders",
    focus:
      "Disturbances in thought, perception, reality testing, and goal-directed behavior.",
    examples: [
      "Schizophrenia",
      "Schizoaffective disorder",
      "Schizophreniform disorder",
      "Brief psychotic disorder",
    ],
  },
  {
    emoji: "🍃",
    family: "Substance-Related and Addictive Disorders",
    focus:
      "Compulsive use despite harm with tolerance, withdrawal, and loss of control.",
    examples: ["Cannabis use disorder", "Alcohol use disorder", "Stimulant use disorder"],
  },
  {
    emoji: "🧠",
    family: "Neurodevelopmental Disorders",
    focus:
      "Early-onset conditions affecting cognition, communication, attention, and behavior.",
    examples: ["ADHD", "Autism spectrum disorder", "Intellectual disability"],
  },
  {
    emoji: "👤",
    family: "Personality Disorders",
    focus:
      "Enduring, inflexible personality patterns causing chronic distress and impairment.",
    examples: ["Borderline personality disorder", "Obsessive-compulsive personality disorder"],
  },
];

export const DISORDER_SPOTLIGHTS: DisorderProfile[] = [
  {
    name: "Schizophrenia",
    family: "Schizophrenia spectrum",
    keyFeatures:
      "Persistent psychotic symptoms may include delusions, hallucinations, disorganized speech/behavior, and negative symptoms such as avolition.",
    typicalOnset: "Late adolescence to early adulthood",
    contextNote:
      "Course and severity are influenced by social support, trauma exposure, substance use, and treatment access.",
    citations: ["DSM-5-TR (APA, 2022)", "NIMH Overview"],
  },
  {
    name: "Schizoaffective Disorder",
    family: "Schizophrenia spectrum",
    keyFeatures:
      "Psychotic symptoms occur with major mood episodes, with at least one period of psychosis that is not exclusively mood-driven.",
    typicalOnset: "Early adulthood",
    contextNote:
      "Mood symptoms and psychosis can fluctuate in prominence across time.",
    citations: ["DSM-5-TR (APA, 2022)", "Malaspina et al., 2013"],
  },
  {
    name: "Schizophreniform Disorder",
    family: "Schizophrenia spectrum",
    keyFeatures:
      "Schizophrenia-like symptom profile with shorter duration than chronic schizophrenia.",
    typicalOnset: "Late adolescence to early adulthood",
    contextNote:
      "Early intervention may improve longer-term functioning and recovery trajectory.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Brief Psychotic Disorder",
    family: "Schizophrenia spectrum",
    keyFeatures:
      "Abrupt psychotic episode lasting more than one day but less than one month, with eventual return to baseline.",
    typicalOnset: "Can occur across adulthood",
    contextNote:
      "Can be associated with acute stressors or postpartum states in some cases.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Bipolar I Disorder",
    family: "Bipolar and related",
    keyFeatures:
      "At least one manic episode, often with depressive episodes across the lifespan.",
    typicalOnset: "Late adolescence to early adulthood",
    contextNote:
      "Stress load, sleep disruption, and substance exposure can amplify episode recurrence risk.",
    citations: ["DSM-5-TR (APA, 2022)", "Post, 1992"],
  },
  {
    name: "Bipolar II Disorder",
    family: "Bipolar and related",
    keyFeatures:
      "Pattern of hypomanic and major depressive episodes without full mania.",
    typicalOnset: "Late adolescence to early adulthood",
    contextNote:
      "Depressive burden is often substantial and may be under-recognized.",
    citations: ["DSM-5-TR (APA, 2022)", "PGC Bipolar GWAS, 2021"],
  },
  {
    name: "Major Depressive Disorder",
    family: "Depressive disorders",
    keyFeatures:
      "Sustained depressed mood and/or anhedonia with cognitive and somatic symptoms causing impairment.",
    typicalOnset: "Any age; common in adolescence and adulthood",
    contextNote:
      "Risk and recovery are shaped by biology, life events, social determinants, and care access.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Post-Traumatic Stress Disorder",
    family: "Trauma- and stressor-related",
    keyFeatures:
      "Re-experiencing, avoidance, negative mood/cognition changes, and hyperarousal after trauma.",
    typicalOnset: "After exposure to a qualifying traumatic event",
    contextNote:
      "Not all trauma-exposed individuals develop PTSD; resilience and support factors matter.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Obsessive-Compulsive Disorder",
    family: "Obsessive-compulsive and related",
    keyFeatures:
      "Intrusive obsessions and repetitive compulsions that are time-consuming and distressing.",
    typicalOnset: "Often adolescence to early adulthood",
    contextNote:
      "Symptoms are ego-dystonic for many individuals and can respond to evidence-based treatment.",
    citations: ["DSM-5-TR (APA, 2022)"],
  },
  {
    name: "Cannabis Use Disorder",
    family: "Substance-related and addictive",
    keyFeatures:
      "Persistent cannabis use despite harm, with impaired control and role disruption.",
    typicalOnset: "Often adolescence or young adulthood",
    contextNote:
      "Severity and risk are affected by potency, frequency, age of onset, and psychiatric vulnerability.",
    citations: ["DSM-5-TR (APA, 2022)", "Murray et al., 2017"],
  },
];

export const STRESS_DIATHESIS_PARAGRAPHS: string[] = [
  "Bipolar disorder reflects a widely distributed human vulnerability rather than a categorical difference between people. In a stress-diathesis model, sustained stressors, including institutional stress such as incarceration, criminal charges, or repeated law-enforcement contact, can increase the probability of illness expression in vulnerable individuals.",
  "A diagnosis is not a marker of lesser humanity. It describes how biology, environment, and lived experience interact over time.",
];

export const NEUROTRANSMITTER_PROFILES: NeurotransmitterProfile[] = [
  {
    name: "Dopamine",
    primaryRole:
      "Helps the brain assign salience (what matters), learn from reward prediction error, and regulate motivation, movement, and goal-directed behavior.",
    whenLow:
      "Can be associated with reduced drive, less pleasure from normally rewarding activities, cognitive slowing, and in some circuits motor slowing.",
    whenHighOrDysregulated:
      "Excessive or poorly timed dopamine signaling can amplify threat/reward salience and has been linked to manic activation and psychosis-spectrum symptoms in vulnerable people.",
    learningNote:
      "Dopamine is not a simple 'pleasure chemical.' It is a precision-learning and salience signal distributed across multiple pathways.",
  },
  {
    name: "GABA",
    primaryRole:
      "The major inhibitory neurotransmitter in the CNS. It dampens over-excitation and helps stabilize network rhythms needed for attention, emotion regulation, and sleep.",
    whenLow:
      "Reduced inhibitory tone can contribute to hyperarousal, anxiety, poor sleep, sensory overload, and increased vulnerability to excitatory runaway states.",
    whenHighOrDysregulated:
      "Excessive inhibition may present as sedation, slowed cognition, or emotional blunting, depending on which circuits are affected.",
    learningNote:
      "Think of GABA as a braking system: healthy function requires balance with excitatory signaling rather than maximal inhibition.",
  },
  {
    name: "Serotonin",
    primaryRole:
      "Modulates mood, anxiety, impulse control, appetite, pain processing, and sleep-wake timing across widespread brain networks.",
    whenLow:
      "Lower serotonergic tone is associated in some individuals with depressed mood, anxiety, irritability, and reduced stress resilience.",
    whenHighOrDysregulated:
      "Overactivation of serotonergic pathways can cause agitation, GI symptoms, tremor, and in severe medication interactions, serotonin toxicity.",
    learningNote:
      "Serotonin is a broad modulatory system, not a single mood dial; effects depend on receptor subtype, brain region, and timescale.",
  },
];

export const GLOSSARY_TERMS: GlossaryEntry[] = [
  {
    term: "Bipolar Disorder",
    definition:
      "A mood disorder characterized by episodes of mania or hypomania and episodes of depression.",
  },
  {
    term: "Schizophrenia",
    definition:
      "A psychotic disorder involving disruptions in perception, thought, and behavior, often with social or occupational decline.",
  },
  {
    term: "Schizoaffective Disorder",
    definition:
      "A condition with both psychotic symptoms and major mood episodes, with some psychosis occurring outside mood episodes.",
  },
  {
    term: "Stress-Diathesis Model",
    definition:
      "A framework in which underlying vulnerability interacts with environmental stress to produce symptom expression.",
  },
  {
    term: "Psychosis",
    definition:
      "A clinical state involving impaired reality testing, such as delusions or hallucinations.",
  },
  {
    term: "Polygenic Risk Score (PRS)",
    definition:
      "A summary score of genetic liability computed from many common variants with small individual effects.",
  },
  {
    term: "Kindling",
    definition:
      "A process in which repeated episodes can lower the threshold for future episodes over time.",
  },
  {
    term: "CB1 Receptor",
    definition:
      "The primary cannabinoid receptor in the brain, strongly involved in THC effects.",
  },
  {
    term: "Dopamine",
    definition:
      "A neurotransmitter involved in salience, motivation, reward-based learning, movement, and goal-directed behavior.",
  },
  {
    term: "GABA",
    definition:
      "The brain's main inhibitory neurotransmitter, helping regulate excitability and stabilize neural signaling.",
  },
  {
    term: "Serotonin",
    definition:
      "A broadly modulatory neurotransmitter involved in mood, anxiety regulation, impulse control, sleep, appetite, and stress responsiveness.",
  },
  {
    term: "ODE (Ordinary Differential Equation)",
    definition:
      "A mathematical equation used to model how variables change continuously over time.",
  },
  {
    term: "Stochastic",
    definition:
      "Containing random variation; stochastic simulations can produce slightly different outputs each run.",
  },
];

export const LEARN_REFERENCES: string[] = [
  "American Psychiatric Association. (2022). Diagnostic and Statistical Manual of Mental Disorders (5th ed., text rev.; DSM-5-TR).",
  "Post, R.M. (1992). Transduction of psychosocial stress into the neurobiology of recurrent affective disorder. American Journal of Psychiatry, 149(8), 999-1010.",
  "Bipolar Disorder Working Group of the Psychiatric Genomics Consortium (2021). Large-scale GWAS meta-analysis of bipolar disorder identifies 64 loci and clarifies the genetic basis of bipolar subtypes. Nature Genetics.",
  "Murray, R.M. et al. (2017). Traditional marijuana, high-potency cannabis and synthetic cannabinoids: increasing risk for psychosis. World Psychiatry, 16(2), 146-149.",
  "Goldbeter, A. (1996). Biochemical Oscillations and Cellular Rhythms. Cambridge University Press.",
  "Russell, J.A. (1980). A circumplex model of affect. Journal of Personality and Social Psychology, 39(6), 1161-1178.",
];

export const PSYCHOTIC_SYMPTOM_DOMAINS: PsychoticDomain[] = [
  {
    domain: "Positive symptoms",
    description:
      "Experiences added to baseline cognition/perception such as fixed false beliefs and abnormal sensory experiences.",
    examples: ["Delusions", "Hallucinations", "Disorganized thought content"],
    clinicalImportance:
      "Often drive acute risk, emergency presentation, and need for rapid stabilization.",
  },
  {
    domain: "Negative symptoms",
    description:
      "Reductions in motivated behavior, emotional expression, and social initiative.",
    examples: ["Avolition", "Blunted affect", "Alogia", "Social withdrawal"],
    clinicalImportance:
      "Strongly linked to long-term functional outcomes and quality of life.",
  },
  {
    domain: "Cognitive symptoms",
    description:
      "Difficulties in attention, working memory, processing speed, and executive planning.",
    examples: ["Attention deficits", "Working-memory impairment", "Executive dysfunction"],
    clinicalImportance:
      "Frequently predicts educational, occupational, and daily-living impairment.",
  },
  {
    domain: "Affective symptoms",
    description:
      "Mood symptoms that can overlap with or alternate against psychotic symptoms.",
    examples: ["Depressive episodes", "Manic/hypomanic episodes", "Anxiety symptoms"],
    clinicalImportance:
      "Essential for differential diagnosis, including schizoaffective and mood disorders with psychotic features.",
  },
];